// <auto-generated />
namespace EF.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class cars : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(cars));
        
        string IMigrationMetadata.Id
        {
            get { return "201511161726059_cars"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
